version: '3.8'

services:
  app:
    container_name: ${APP_NAME}_app
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
        - ${LARAVEL_PORT}:80
    volumes:
      - '.:/var/www/html'
    networks:
      - ${APP_NAME}_network
    depends_on:
      - redis
  db:
    container_name: ${APP_NAME}_db
    image: 'postgres:13.5-alpine'
    ports:
      - '${DB_PORT_DOCKER:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - './docker/db-data:/var/lib/postgresql/data'
    networks:
      - ${APP_NAME}_network
  redis:
    container_name: ${APP_NAME}_redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - './docker/redis:/data'
    networks:
      - ${APP_NAME}_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
networks:
  transfer_flow_network:
    driver: bridge
